#pragma once

#import "SimInterface.tlb"

// code generated by #import is almost correct. sigh...
// ...The uuid of the generated interfaces won't QueryInterface for IDispatch like
// these kludges will
interface __declspec(uuid("00020400-0000-0000-C000-000000000046")) /* IID_IDispatch */
    IKnowDispatchIsManager : ContestSuperSimDispLib::ISuperSimManager
{};
_COM_SMARTPTR_TYPEDEF(IKnowDispatchIsManager,  __uuidof(IKnowDispatchIsManager));

interface __declspec(uuid("00020400-0000-0000-C000-000000000046"))
    IKnowDispatchIsCwSimulator : ContestSuperSimDispLib::ICwSidetoneSimulator
{};
_COM_SMARTPTR_TYPEDEF(IKnowDispatchIsCwSimulator,  __uuidof(IKnowDispatchIsCwSimulator));

interface __declspec(uuid("00020400-0000-0000-C000-000000000046"))
    IKnowDispatchIsRadioSimulator : ContestSuperSimDispLib::IRadioSimulator
{};
_COM_SMARTPTR_TYPEDEF(IKnowDispatchIsRadioSimulator,  __uuidof(IKnowDispatchIsRadioSimulator));
